# Generated by Django 6.0.6 on 2026-08-04 14:19

import copycat.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=copycat.utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=copycat.utils.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
